version: 2

jobs:
  build:
    docker:
      - image: circleci/node:7.10
    
    working_directory: ~/repo
    
    steps:
      - checkout

      #
    
      # Download and cache dependencies
      - restore_cache:
          keys:
            - vi-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-depemdencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: vi-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: sleep 11m
      - run: npm test
      - run: echo Hello Pluralsight